name: Java CI

on:
  push:
    branches: ['main', 'dev']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Setup Java 17'
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: 'Build with Maven'
        run: mvn --batch-mode -DskipTests package

      - name: 'Run tests'
        run: mvn --batch-mode test

      - name: 'Report results'
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: 'Maven tests'
          path: './.reports/*.xml'
          reporter: java-junit
          fail-on-error: true